version: '3.8'

services:
  plataforma-auth:
    build: ./auth
    container_name: plataforma-auth
    networks:
      - plataforma-testes
    ports:
      - 7000:7000
    depends_on:
      - mysql-db
  plataforma-cats:
    build: ./cats-api
    container_name: plataforma-cats
    networks:
      - plataforma-testes
    ports:
      - 3000:3000
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:8.0.35
    networks:
      - plataforma-testes
    container_name: mysql-db
    ports:
      - 33406:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    container_name: jaeger
#    networks:
#      - plataforma-testes
#    ports:
#      - 6831:6831/udp
#      - 6832:6832/udp
#      - 5778:5778
#      - 16686:16686
#      - 4317:4317
#      - 4318:4318
#      - 14250:14250
#      - 14268:14268
#      - 14269:14269
#      - 9411:9411

networks:
  plataforma-testes:
    driver: bridge
